-- =============================================================================
-- CareTrack Hospital Management System
-- MSSQL → PostgreSQL Migration
-- Source Database: CareTrack (SQL Server)
-- Target Database: PostgreSQL
-- Migration Date: 2026-01-30
-- =============================================================================
-- Migration Constraints Applied:
--   allow_application_changes = false
--   has_crystal_reports        = true
--   has_external_integrations  = true
--   multiple_resultset_strategy = refcursor
-- =============================================================================

-- =============================================================================
-- SECTION 1: EXTENSIONS
-- =============================================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =============================================================================
-- SECTION 2: SCHEMAS
-- =============================================================================
-- Create dbo schema to preserve original object namespacing
CREATE SCHEMA IF NOT EXISTS dbo;

-- =============================================================================
-- SECTION 3: BASE TABLES (no FK dependencies)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: dbo.Department
-- Original: [dbo].[Department]
-- Changes:
--   - PRIMARY KEY CLUSTERED → PRIMARY KEY (PostgreSQL has no clustered indexes)
--   - UNIQUE NONCLUSTERED → UNIQUE constraint
--   - Identifier options (PAD_INDEX, etc.) removed (not supported in PostgreSQL)
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.department (
    deptno      integer         NOT NULL,
    deptname    varchar(30)     NOT NULL,
    description varchar(1000)   NULL,
    CONSTRAINT pk_dept PRIMARY KEY (deptno),
    CONSTRAINT uq_dept_name UNIQUE (deptname)
);

-- -----------------------------------------------------------------------------
-- Table: dbo.LoginTable
-- Original: [dbo].[LoginTable]
-- Changes:
--   - IDENTITY(1,1) → GENERATED BY DEFAULT AS IDENTITY
--   - UNIQUE NONCLUSTERED on Email → UNIQUE constraint
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.logintable (
    loginid  integer         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    password varchar(20)     NOT NULL,
    email    varchar(30)     NOT NULL,
    type     integer         NOT NULL,
    CONSTRAINT pk_login PRIMARY KEY (loginid),
    CONSTRAINT uq_login_email UNIQUE (email)
);

-- -----------------------------------------------------------------------------
-- Table: dbo.OtherStaff
-- Original: [dbo].[OtherStaff]
-- Changes:
--   - IDENTITY(1,1) → GENERATED BY DEFAULT AS IDENTITY
--   - float → double precision
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.otherstaff (
    staffid               integer         GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                  varchar(30)     NOT NULL,
    phone                 char(11)        NULL,
    address               varchar(30)     NULL,
    designation           varchar(15)     NOT NULL,
    gender                char(1)         NOT NULL,
    birthdate             date            NULL,
    highest_qualification varchar(50)     NULL,
    salary                double precision NULL,
    CONSTRAINT pk_staff PRIMARY KEY (staffid)
);

-- =============================================================================
-- SECTION 4: TABLES WITH FK DEPENDENCIES (created after base tables)
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Table: dbo.Doctor
-- Original: [dbo].[Doctor]
-- Changes:
--   - float → double precision
--   - DEFAULT ((0)) for Patients_Treated added inline
--   - FK to Department added in FK section below
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.doctor (
    doctorid          integer             NOT NULL,
    name              varchar(30)         NOT NULL,
    phone             char(11)            NULL,
    address           varchar(40)         NULL,
    birthdate         date                NOT NULL,
    gender            char(1)             NOT NULL,
    deptno            integer             NOT NULL,
    charges_per_visit double precision    NOT NULL,
    monthlysalary     double precision    NULL,
    reputeindex       double precision    NULL,
    patients_treated  integer             NOT NULL DEFAULT 0,
    qualification     varchar(100)        NOT NULL,
    specialization    varchar(100)        NULL,
    work_experience   integer             NULL,
    status            integer             NOT NULL,
    CONSTRAINT pk_doctor PRIMARY KEY (doctorid)
);

-- -----------------------------------------------------------------------------
-- Table: dbo.Patient
-- Original: [dbo].[Patient]
-- Changes:
--   - FK PatientID → LoginTable.LoginID added in FK section below
-- NOTE: In the original schema, Patient.PatientID references LoginTable.LoginID
--       (the patient's login ID IS the patient ID — no separate identity column)
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.patient (
    patientid integer     NOT NULL,
    name      varchar(30) NOT NULL,
    phone     char(11)    NULL,
    address   varchar(40) NULL,
    birthdate date        NOT NULL,
    gender    char(1)     NOT NULL,
    CONSTRAINT pk_patient PRIMARY KEY (patientid)
);

-- -----------------------------------------------------------------------------
-- Table: dbo.Appointment
-- Original: [dbo].[Appointment]
-- Changes:
--   - IDENTITY(1,1) → GENERATED BY DEFAULT AS IDENTITY
--   - datetime → timestamp without time zone
--   - float → double precision
--   - FKs to Patient and Doctor added in FK section below
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.appointment (
    appointid            integer             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    doctorid             integer             NULL,
    patientid            integer             NULL,
    date                 timestamp without time zone NULL,
    appointment_status   integer             NULL,
    bill_amount          double precision    NULL,
    bill_status          varchar(10)         NULL,
    doctornotification   integer             NULL,
    patientnotification  integer             NULL,
    feedbackstatus       integer             NULL,
    disease              varchar(100)        NULL,
    progress             varchar(100)        NULL,
    prescription         varchar(100)        NULL,
    CONSTRAINT pk_appoint PRIMARY KEY (appointid)
);

-- -----------------------------------------------------------------------------
-- Table: dbo.ProfileImages
-- Original: [dbo].[ProfileImages]
-- Changes:
--   - IDENTITY(1,1) → GENERATED BY DEFAULT AS IDENTITY
--   - datetime2(7) → timestamp without time zone
--   - bit → boolean
--   - DEFAULT (getutcdate()) → DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
--   - DEFAULT ((1)) → DEFAULT TRUE
--   - FK to LoginTable added in FK section below
-- -----------------------------------------------------------------------------
CREATE TABLE dbo.profileimages (
    imageid         integer             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    loginid         integer             NOT NULL,
    s3bucketname    varchar(100)        NOT NULL,
    s3key           varchar(500)        NOT NULL,
    filename        varchar(255)        NOT NULL,
    fileextension   varchar(10)         NOT NULL,
    contenttype     varchar(100)        NOT NULL,
    filesizebytes   bigint              NOT NULL,
    s3url           varchar(1000)       NULL,
    uploadedat      timestamp without time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updatedat       timestamp without time zone NULL,
    isactive        boolean             NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_profimg PRIMARY KEY (imageid)
);

-- =============================================================================
-- SECTION 5: INDEXES
-- =============================================================================

-- IX_ProfileImages_LoginID → ix_profimg_loginid
CREATE INDEX ix_profimg_loginid
    ON dbo.profileimages (loginid);

-- IX_ProfileImages_LoginID_Unique → uq_profimg_loginid
-- Original was a UNIQUE NONCLUSTERED index; converted to unique index
CREATE UNIQUE INDEX uq_profimg_loginid
    ON dbo.profileimages (loginid);

-- =============================================================================
-- SECTION 6: FOREIGN KEYS
-- (All tables must exist before FK constraints are added)
-- =============================================================================

-- Appointment → Patient
ALTER TABLE dbo.appointment
    ADD CONSTRAINT fk_appoint_patient
    FOREIGN KEY (patientid) REFERENCES dbo.patient (patientid);

-- Appointment → Doctor (ON DELETE SET NULL preserved)
ALTER TABLE dbo.appointment
    ADD CONSTRAINT fk_appoint_doctor
    FOREIGN KEY (doctorid) REFERENCES dbo.doctor (doctorid)
    ON DELETE SET NULL;

-- Doctor → Department
ALTER TABLE dbo.doctor
    ADD CONSTRAINT fk_doctor_dept
    FOREIGN KEY (deptno) REFERENCES dbo.department (deptno);

-- Patient → LoginTable (PatientID = LoginID — patient uses login record as PK)
ALTER TABLE dbo.patient
    ADD CONSTRAINT fk_patient_login
    FOREIGN KEY (patientid) REFERENCES dbo.logintable (loginid);

-- ProfileImages → LoginTable (ON DELETE CASCADE preserved)
ALTER TABLE dbo.profileimages
    ADD CONSTRAINT fk_profimg_login
    FOREIGN KEY (loginid) REFERENCES dbo.logintable (loginid)
    ON DELETE CASCADE;

-- =============================================================================
-- SECTION 7: VIEWS
-- =============================================================================

-- -----------------------------------------------------------------------------
-- View: dbo.deptinfo
-- Original: [dbo].[deptInfo]
-- Changes: None (straightforward translation; != → <> is equivalent in PG)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.deptinfo AS
SELECT
    deptname,
    description,
    count(dept.deptno) AS "Number of Doctors"
FROM dbo.department dept
JOIN dbo.doctor d ON dept.deptno = d.deptno
WHERE d.status <> 0
GROUP BY dept.deptno, deptname, description;

-- -----------------------------------------------------------------------------
-- View: dbo.total_patient
-- Original: [dbo].[Total_Patient]
-- Changes: Column alias uses double-quotes for PostgreSQL compatibility
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.total_patient AS
SELECT COUNT(patientid) AS "Total Patients"
FROM dbo.patient;

-- -----------------------------------------------------------------------------
-- View: dbo.total_doctors
-- Original: [dbo].[Total_Doctors]
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.total_doctors AS
SELECT COUNT(doctor.doctorid) AS "Total Doctors"
FROM dbo.doctor
WHERE doctor.status <> 0;

-- -----------------------------------------------------------------------------
-- View: dbo.income
-- Original: [dbo].[Income]
-- Changes:
--   - DATEDIFF(MONTH, date, GETDATE()) = 0 →
--     DATE_PART('year', AGE(CURRENT_TIMESTAMP, date)) * 12 +
--     DATE_PART('month', AGE(CURRENT_TIMESTAMP, date)) = 0
--     (simplified: same month/year check using date_trunc)
--   - GETDATE() → CURRENT_TIMESTAMP
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.income AS
SELECT SUM(bill_amount) AS income
FROM dbo.appointment
WHERE appointment.bill_status = 'Paid'
  AND DATE_PART('year',  AGE(CURRENT_TIMESTAMP, appointment.date)) * 12
    + DATE_PART('month', AGE(CURRENT_TIMESTAMP, appointment.date)) = 0;

-- -----------------------------------------------------------------------------
-- View: dbo.department_view
-- Original: [dbo].[Department_View]
-- Changes:
--   - SELECT TOP 20 ... ORDER BY → SELECT ... ORDER BY ... LIMIT 20
--     (LIMIT must appear at end of query; ORDER BY inside a plain view is
--      not guaranteed in PostgreSQL — wrapped in a subquery for correctness)
--   - WITH SCHEMABINDING removed (not supported in PostgreSQL)
-- NOTE: PostgreSQL does not allow ORDER BY in a plain view without LIMIT.
--       The TOP 20 + ORDER BY is preserved via a subquery.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.department_view AS
SELECT id, name, description, "Number of Doctors"
FROM (
    SELECT
        department.deptno   AS id,
        department.deptname AS name,
        department.description,
        count(department.deptno) AS "Number of Doctors"
    FROM dbo.department
    JOIN dbo.doctor ON department.deptno = doctor.deptno
    WHERE doctor.status <> 0
    GROUP BY department.deptno, department.deptname, department.description
    ORDER BY department.deptno
    LIMIT 20
) sub;

-- -----------------------------------------------------------------------------
-- View: dbo.appointment_view
-- Original: [dbo].[Appointment_view]
-- Changes:
--   - DATEDIFF(MONTH, A.Date, GETDATE()) = 0 → same-month check via AGE()
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.appointment_view AS
SELECT
    a.appointid,
    doctor.name,
    patient.patientid,
    a.date
FROM dbo.appointment a
JOIN dbo.patient   ON patient.patientid = a.patientid
JOIN dbo.doctor    ON doctor.doctorid   = a.doctorid
WHERE DATE_PART('year',  AGE(CURRENT_TIMESTAMP, a.date)) * 12
    + DATE_PART('month', AGE(CURRENT_TIMESTAMP, a.date)) = 0;

-- -----------------------------------------------------------------------------
-- View: dbo.staff_view
-- Original: [dbo].[STAFF_VIEW]
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.staff_view AS
SELECT staffid AS id, name, designation
FROM dbo.otherstaff;

-- -----------------------------------------------------------------------------
-- View: dbo.patient_view
-- Original: [dbo].[PATIENT_VIEW]
-- -----------------------------------------------------------------------------
CREATE OR REPLACE VIEW dbo.patient_view AS
SELECT patient.patientid AS id, patient.name, patient.phone
FROM dbo.patient;

-- =============================================================================
-- SECTION 8: FUNCTIONS (converted from Stored Procedures)
-- =============================================================================
-- Migration constraint: allow_application_changes = false, has_crystal_reports = true
-- Strategy: REFCURSOR pattern for multi-result-set procedures;
--           OUT parameters for single-output procedures.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Function: dbo.fnsplitstring
-- Original: [dbo].[fnSplitString] (table-valued function)
-- Changes:
--   - NVARCHAR(MAX) → text
--   - CHAR(1) → char(1)
--   - Table-valued function → RETURNS TABLE using RETURN QUERY with
--     regexp_split_to_table for idiomatic PostgreSQL
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.fnsplitstring(
    p_string    text,
    p_delimiter char(1)
)
RETURNS TABLE(splitdata text)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT s.val
    FROM regexp_split_to_table(p_string, regexp_quote(p_delimiter::text)) AS s(val)
    WHERE s.val <> '';
END;
$$;

-- Helper: regexp_quote is not built-in; create a simple escape helper
-- (used internally by fnsplitstring to escape the delimiter for regexp)
CREATE OR REPLACE FUNCTION dbo.regexp_quote(p_str text)
RETURNS text
LANGUAGE sql
IMMUTABLE STRICT
AS $$
    SELECT regexp_replace(p_str, '([!$()*+.:<=>?[\\\]^{|}-])', '\\\1', 'g');
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.adddoctor
-- Original: [dbo].[AddDoctor]
-- Changes:
--   - @variable → p_variable naming
--   - INSERT INTO LoginTable values(...) → explicit column list (required)
--   - INSERT INTO Doctor values(...) → explicit column list (required)
--   - SCOPE_IDENTITY() / @@IDENTITY → lastval() / RETURNING
--   - Single result set (no output) → RETURNS void
-- NOTE: Original INSERT INTO LoginTable/Doctor used positional VALUES without
--       column names. Explicit column names added for PostgreSQL compatibility.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.adddoctor(
    p_name      varchar(50),
    p_email     varchar(50),
    p_password  varchar(50),
    p_birthdate date,
    p_dept      integer,
    p_gender    char(1),
    p_address   varchar(50),
    p_exp       integer,
    p_salary    integer,
    p_spec      varchar(50),
    p_phone     varchar(50),
    p_charges   integer,
    p_qual      varchar(50)
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_id integer;
BEGIN
    INSERT INTO dbo.logintable (password, email, type)
    VALUES (p_password, p_email, 2);

    SELECT loginid INTO v_id
    FROM dbo.logintable
    WHERE email = p_email;

    INSERT INTO dbo.doctor (
        doctorid, name, phone, address, birthdate, gender,
        deptno, charges_per_visit, monthlysalary, reputeindex,
        patients_treated, qualification, specialization, work_experience, status
    )
    VALUES (
        v_id, p_name, p_phone, p_address, p_birthdate, p_gender,
        p_dept, p_charges, p_salary, 0,
        0, p_qual, p_spec, p_exp, -1
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.addstaff
-- Original: [dbo].[AddStaff]
-- Changes:
--   - INSERT INTO OtherStaff VALUES(...) → explicit column list
-- NOTE: Original column order in VALUES was: Name, phone, Address, designation,
--       gender, BirthDate, Qualification, Salary
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.addstaff(
    p_name          varchar(50),
    p_birthdate     date,
    p_phone         varchar(30),
    p_gender        varchar(1),
    p_designation   varchar(30),
    p_address       varchar(50),
    p_salary        integer,
    p_qualification varchar(50)
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO dbo.otherstaff (name, phone, address, designation, gender, birthdate, highest_qualification, salary)
    VALUES (p_name, p_phone, p_address, p_designation, p_gender, p_birthdate, p_qualification, p_salary);
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.approve_appointment
-- Original: [dbo].[APPROVE_APPOINTMENT]
-- Changes: Simple UPDATE; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.approve_appointment(
    p_appoint_id integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE dbo.appointment
    SET appointment_status = 1,
        patientnotification = 2
    WHERE appointid = p_appoint_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.checkdoctoremail
-- Original: [dbo].[CheckDoctorEmail]
-- Changes:
--   - Single OUT parameter @status int output → OUT p_status integer
--   - RETURNS INTEGER (matches single OUT parameter type)
--   - No RETURN value statement (OUT parameter returned automatically)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.checkdoctoremail(
    p_email  varchar(30),
    OUT p_status integer
)
RETURNS integer
LANGUAGE plpgsql
AS $$
BEGIN
    p_status := 0;
    IF EXISTS (SELECT 1 FROM dbo.logintable WHERE email = p_email) THEN
        p_status := 1;
    END IF;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.delete_appointment
-- Original: [dbo].[delete_APPOINTMENT]
-- Changes: Simple UPDATE; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.delete_appointment(
    p_appoint_id integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE dbo.appointment
    SET appointment_status = 4,
        patientnotification = 2
    WHERE appointid = p_appoint_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.deletedoctor
-- Original: [dbo].[DeleteDoctor]
-- Changes: Simple DELETE; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.deletedoctor(
    p_id integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM dbo.doctor WHERE doctorid = p_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.deletestaff
-- Original: [dbo].[DELETESTAFF]
-- Changes: Simple DELETE; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.deletestaff(
    p_id integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    DELETE FROM dbo.otherstaff WHERE staffid = p_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.doctor_information_by_id1
-- Original: [dbo].[Doctor_Information_By_ID1]
-- Changes:
--   - SELECT * FROM doctor → RETURNS TABLE with explicit columns
--   - RETURNS TABLE for result set
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.doctor_information_by_id1(
    p_id integer
)
RETURNS TABLE(
    doctorid          integer,
    name              varchar(30),
    phone             char(11),
    address           varchar(40),
    birthdate         date,
    gender            char(1),
    deptno            integer,
    charges_per_visit double precision,
    monthlysalary     double precision,
    reputeindex       double precision,
    patients_treated  integer,
    qualification     varchar(100),
    specialization    varchar(100),
    work_experience   integer,
    status            integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        d.doctorid, d.name, d.phone, d.address, d.birthdate, d.gender,
        d.deptno, d.charges_per_visit, d.monthlysalary, d.reputeindex,
        d.patients_treated, d.qualification, d.specialization,
        d.work_experience, d.status
    FROM dbo.doctor d
    WHERE d.doctorid = p_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.finishedpaid
-- Original: [dbo].[finishedPaid]
-- Changes: Two UPDATEs; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.finishedpaid(
    p_docid     integer,
    p_appointid integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE dbo.appointment
    SET bill_status         = 'paid',
        appointment_status  = 3,
        patientnotification = 2,
        bill_amount         = (SELECT charges_per_visit FROM dbo.doctor WHERE doctorid = p_docid),
        feedbackstatus      = 2
    WHERE appointid = p_appointid;

    UPDATE dbo.doctor
    SET patients_treated = patients_treated + 1
    WHERE doctorid = p_docid;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.finishedunpaid
-- Original: [dbo].[finishedUnpaid]
-- Changes: Two UPDATEs; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.finishedunpaid(
    p_docid     integer,
    p_appointid integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE dbo.appointment
    SET bill_status         = 'Unpaid',
        appointment_status  = 3,
        patientnotification = 2,
        bill_amount         = (SELECT charges_per_visit FROM dbo.doctor WHERE doctorid = p_docid),
        feedbackstatus      = 2
    WHERE appointid = p_appointid;

    UPDATE dbo.doctor
    SET patients_treated = patients_treated + 1
    WHERE doctorid = p_docid;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.generate_bill
-- Original: [dbo].[generate_bill]
-- Changes: Simple SELECT; RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.generate_bill(
    p_did integer
)
RETURNS TABLE(charges double precision)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT d.charges_per_visit AS charges
    FROM dbo.doctor d
    WHERE d.doctorid = p_did;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.get_appointment
-- Original: [dbo].[get_appointment]
-- Changes: Simple SELECT; RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.get_appointment(
    p_appoint_id integer
)
RETURNS TABLE(
    appointid           integer,
    date                timestamp without time zone,
    appointment_status  integer,
    bill_amount         double precision,
    bill_status         varchar(10),
    disease             varchar(100),
    progress            varchar(100),
    prescription        varchar(100)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.appointid, a.date, a.appointment_status,
        a.bill_amount, a.bill_status, a.disease, a.progress, a.prescription
    FROM dbo.appointment a
    WHERE a.appointid = p_appoint_id;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.get_doctor_profile
-- Original: [dbo].[GET_DOCTOR_PROFILE]
-- Changes:
--   - Multiple OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - DATEDIFF(YEAR, BirthDate, GETDATE()) →
--     EXTRACT(YEAR FROM AGE(CURRENT_TIMESTAMP, birthdate))::integer
--   - No RETURN value statement (OUT parameters returned automatically)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.get_doctor_profile(
    p_did           integer,
    OUT p_name      varchar(20),
    OUT p_phone     char(15),
    OUT p_gender    varchar(2),
    OUT p_charges   double precision,
    OUT p_ri        double precision,
    OUT p_ptreated  integer,
    OUT p_qualification  varchar(100),
    OUT p_specialization varchar(50),
    OUT p_worke     integer,
    OUT p_age       integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        d.name,
        d.phone,
        d.gender,
        d.charges_per_visit,
        d.reputeindex,
        d.patients_treated,
        d.qualification,
        d.specialization,
        d.work_experience,
        EXTRACT(YEAR FROM AGE(CURRENT_TIMESTAMP, d.birthdate))::integer
    INTO
        p_name, p_phone, p_gender, p_charges, p_ri,
        p_ptreated, p_qualification, p_specialization, p_worke, p_age
    FROM dbo.doctor d
    WHERE d.doctorid = p_did;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.get_staff
-- Original: [dbo].[GET_STAFF]
-- Changes:
--   - Multiple OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - Note: original had @gender assigned twice (bug preserved as-is)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.get_staff(
    p_id        integer,
    OUT p_name  varchar(20),
    OUT p_phone char(15),
    OUT p_gender varchar(2),
    OUT p_address varchar(100),
    OUT p_desig  varchar(100),
    OUT p_sal    integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        s.name,
        s.phone,
        s.gender,
        s.address,
        s.designation,
        s.salary::integer
    INTO p_name, p_phone, p_gender, p_address, p_desig, p_sal
    FROM dbo.otherstaff s
    WHERE s.staffid = p_id;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.insertinappointmenttable
-- Original: [dbo].[insertInAppointmentTable]
-- Changes:
--   - CONVERT(VARCHAR(11), GETDATE(), 6) → TO_CHAR(CURRENT_DATE, 'DD Mon YY')
--     (format 6 = DD Mon YY in SQL Server)
--   - String date construction → direct timestamp arithmetic
--   - CONVERT(datetime, @date) → timestamp cast
--   - INSERT INTO Appointment values(...) → explicit column list
-- NOTE: The original builds a datetime string from today's date + hour slot.
--       Rewritten using PostgreSQL date/time arithmetic for correctness.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.insertinappointmenttable(
    p_pid       integer,
    p_did       integer,
    p_freeslot  integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_slot  integer;
    v_datea timestamp without time zone;
BEGIN
    v_slot := p_freeslot;
    IF v_slot < 9 THEN
        v_slot := v_slot + 12;
    END IF;

    -- Build today's date at the given hour slot
    v_datea := date_trunc('day', CURRENT_TIMESTAMP) + (v_slot * INTERVAL '1 hour');

    INSERT INTO dbo.appointment (
        doctorid, patientid, date, appointment_status,
        bill_amount, bill_status, doctornotification, patientnotification,
        feedbackstatus, disease, progress, prescription
    )
    VALUES (
        p_did, p_pid, v_datea, 2,
        NULL, NULL, 2, 1,
        NULL, NULL, NULL, NULL
    );
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.login
-- Original: [dbo].[Login]
-- Changes:
--   - Three OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - Crystal Reports compatible: single function call, OUT params as columns
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.login(
    p_email     varchar(30),
    p_password  varchar(20),
    OUT p_status integer,
    OUT p_id     integer,
    OUT p_type   integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM dbo.logintable WHERE email = p_email) THEN
        IF p_password = (SELECT password FROM dbo.logintable WHERE email = p_email) THEN
            SELECT loginid, type
            INTO p_id, p_type
            FROM dbo.logintable
            WHERE email = p_email;
            p_status := 0;
        ELSE
            p_status := 2;
            p_id     := 0;
            p_type   := 0;
        END IF;
    ELSE
        p_status := 1;
        p_id     := 0;
        p_type   := 0;
    END IF;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.patientsignup
-- Original: [dbo].[PatientSignup]
-- Changes:
--   - Two OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - INSERT INTO LoginTable values(...) → explicit column list
--   - INSERT INTO Patient values(...) → explicit column list
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.patientsignup(
    p_name      varchar(20),
    p_phone     char(15),
    p_address   varchar(40),
    p_date      date,
    p_gender    char(1),
    p_password  varchar(20),
    p_email     varchar(30),
    OUT p_status integer,
    OUT p_id     integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM dbo.logintable WHERE email = p_email) THEN
        INSERT INTO dbo.logintable (password, email, type)
        VALUES (p_password, p_email, 1);

        SELECT loginid INTO p_id
        FROM dbo.logintable
        WHERE email = p_email;

        INSERT INTO dbo.patient (patientid, name, phone, address, birthdate, gender)
        VALUES (p_id, p_name, p_phone, p_address, p_date, p_gender);

        p_status := 1;
    ELSE
        p_status := 0;
        p_id     := NULL;
    END IF;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.pending_appointments2
-- Original: [dbo].[PENDING_APPOINTMENTS2]
-- Changes:
--   - DATEDIFF(DAY, A.Date, GETDATE()) = 0 → DATE(a.date) = CURRENT_DATE
--   - RETURNS TABLE for result set
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.pending_appointments2(
    p_doctor_id integer
)
RETURNS TABLE(
    appointid           integer,
    patient_name        varchar(30),
    date                timestamp without time zone,
    appointment_status  integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.appointid,
        p.name          AS patient_name,
        a.date,
        a.appointment_status
    FROM dbo.appointment a
    JOIN dbo.patient p ON a.patientid = p.patientid
    WHERE a.doctorid = p_doctor_id
      AND a.appointment_status = 2
      AND DATE(a.date) = CURRENT_DATE;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievebillhistory
-- Original: [dbo].[RetrieveBillHistory]
-- Changes:
--   - Has both a result set AND an OUT parameter (@count)
--   - CANNOT mix OUT parameters with RETURNS TABLE in PostgreSQL
--   - Strategy: REFCURSOR pattern (constraint: allow_application_changes=false)
--   - CONVERT(VARCHAR(11), [date], 106) → TO_CHAR(date, 'DD Mon YYYY')
--     (format 106 = DD Mon YYYY in SQL Server)
-- BREAKING CHANGE NOTE: Application must read two cursors:
--   ref_bills  → bill history rows
--   ref_count  → single row with count value
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievebillhistory(
    p_pid           integer,
    OUT ref_bills   REFCURSOR,
    OUT ref_count   REFCURSOR
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    OPEN ref_bills FOR
        SELECT
            TO_CHAR(a.date, 'DD Mon YYYY') AS "Date",
            d.name                          AS "Doctor's Name",
            a.bill_amount                   AS "Bill Amount",
            a.bill_status                   AS "Bill Status"
        FROM dbo.appointment a
        JOIN dbo.doctor d ON a.doctorid = d.doctorid
        WHERE a.patientid = p_pid
          AND a.appointment_status = 3;

    OPEN ref_count FOR
        SELECT COUNT(*) AS count
        FROM dbo.appointment
        WHERE patientid = p_pid
          AND appointment_status = 3;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievecurrentappointment
-- Original: [dbo].[RetrieveCurrentAppointment]
-- Changes:
--   - Three OUT parameters + complex logic → RETURNS SETOF record
--   - DATEPART(day/month/year, ...) → EXTRACT(... FROM ...)
--   - CONVERT(VARCHAR(19), [date]) → TO_CHAR(date, 'YYYY-MM-DD HH24:MI:SS')
--   - GETDATE() → CURRENT_TIMESTAMP
--   - Outdated appointment cleanup logic preserved
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievecurrentappointment(
    p_pid       integer,
    OUT p_dname  varchar(30),
    OUT p_timings varchar(30),
    OUT p_count  integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
DECLARE
    v_day    integer;
    v_month  integer;
    v_year   integer;
    v_aday   integer;
    v_amonth integer;
    v_ayear  integer;
BEGIN
    IF EXISTS (SELECT 1 FROM dbo.appointment WHERE patientid = p_pid AND appointment_status = 2) THEN
        v_day   := EXTRACT(DAY   FROM CURRENT_TIMESTAMP)::integer;
        v_month := EXTRACT(MONTH FROM CURRENT_TIMESTAMP)::integer;
        v_year  := EXTRACT(YEAR  FROM CURRENT_TIMESTAMP)::integer;

        SELECT
            EXTRACT(DAY   FROM date)::integer,
            EXTRACT(MONTH FROM date)::integer,
            EXTRACT(YEAR  FROM date)::integer
        INTO v_aday, v_amonth, v_ayear
        FROM dbo.appointment
        WHERE patientid = p_pid AND appointment_status = 2;

        SELECT d.name, TO_CHAR(a.date, 'YYYY-MM-DD HH24:MI:SS')
        INTO p_dname, p_timings
        FROM dbo.appointment a
        JOIN dbo.doctor d ON a.doctorid = d.doctorid
        WHERE a.patientid = p_pid AND a.appointment_status = 2;

        IF (v_aday <> v_day OR v_amonth <> v_month OR v_ayear <> v_year) THEN
            DELETE FROM dbo.appointment
            WHERE patientid = p_pid AND appointment_status = 2;
            p_count := 3;
        ELSE
            p_count := 2;
        END IF;
    ELSE
        IF EXISTS (SELECT 1 FROM dbo.appointment WHERE patientid = p_pid AND appointment_status = 1) THEN
            SELECT d.name, TO_CHAR(a.date, 'YYYY-MM-DD HH24:MI:SS')
            INTO p_dname, p_timings
            FROM dbo.appointment a
            JOIN dbo.doctor d ON a.doctorid = d.doctorid
            WHERE a.patientid = p_pid AND a.appointment_status = 1;
            p_count := 1;
        ELSE
            p_count := 0;
        END IF;
    END IF;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievedeptdoctorinfo
-- Original: [dbo].[RetrieveDeptDoctorInfo]
-- Changes: Simple SELECT; RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievedeptdoctorinfo(
    p_deptname varchar(30)
)
RETURNS TABLE(
    doctorid        integer,
    doctor_name     varchar(30),
    specialization  varchar(100),
    deptname        varchar(30)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        d.doctorid,
        d.name          AS doctor_name,
        d.specialization,
        dept.deptname
    FROM dbo.department dept
    JOIN dbo.doctor d ON dept.deptno = d.deptno
    WHERE dept.deptname = p_deptname
      AND d.status <> 0;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievedoctordata
-- Original: [dbo].[RetrieveDoctorData]
-- Changes:
--   - Multiple OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - DATEDIFF(YEAR, BirthDate, GETDATE()) → EXTRACT(YEAR FROM AGE(...))
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievedoctordata(
    p_did           integer,
    OUT p_name      varchar(30),
    OUT p_phone     char(11),
    OUT p_gender    varchar(2),
    OUT p_charges   double precision,
    OUT p_ri        double precision,
    OUT p_ptreated  integer,
    OUT p_qualification  varchar(100),
    OUT p_specialization varchar(100),
    OUT p_worke     integer,
    OUT p_age       integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        d.name,
        d.phone,
        d.gender,
        d.charges_per_visit,
        d.reputeindex,
        d.patients_treated,
        d.qualification,
        d.specialization,
        d.work_experience,
        EXTRACT(YEAR FROM AGE(CURRENT_TIMESTAMP, d.birthdate))::integer
    INTO
        p_name, p_phone, p_gender, p_charges, p_ri,
        p_ptreated, p_qualification, p_specialization, p_worke, p_age
    FROM dbo.doctor d
    WHERE d.doctorid = p_did;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievefreeslots
-- Original: [dbo].[RetrieveFreeSlots]
-- Changes:
--   - WHILE loop preserved; DATEPART → EXTRACT
--   - GETDATE() → CURRENT_TIMESTAMP
--   - CAST(@tempHour AS VARCHAR(5)) → v_temphour::varchar(5)
--   - dbo.fnSplitString(@hoursList, ',') → dbo.fnsplitstring(v_hourslist, ',')
--   - Has OUT parameter @count AND a result set → REFCURSOR pattern
--   - ref_slots cursor returns the free slot strings
--   - ref_count cursor returns the count
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievefreeslots(
    p_did           integer,
    p_pid           integer,
    OUT ref_slots   REFCURSOR,
    OUT ref_count   REFCURSOR
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
DECLARE
    v_month       integer;
    v_year        integer;
    v_day         integer;
    v_hourslist   varchar(100);
    v_currenthour integer;
    v_count       integer;
    v_tempt       varchar(10);
    v_temphour    integer;
BEGIN
    v_month := EXTRACT(MONTH FROM CURRENT_TIMESTAMP)::integer;
    v_year  := EXTRACT(YEAR  FROM CURRENT_TIMESTAMP)::integer;
    v_day   := EXTRACT(DAY   FROM CURRENT_TIMESTAMP)::integer;

    v_currenthour := 9;
    v_count       := 0;
    v_hourslist   := '';
    v_temphour    := 0;

    WHILE v_currenthour <> 18 LOOP
        IF NOT EXISTS (
            SELECT 1 FROM dbo.appointment
            WHERE EXTRACT(YEAR  FROM date)::integer = v_year
              AND EXTRACT(MONTH FROM date)::integer = v_month
              AND EXTRACT(DAY   FROM date)::integer = v_day
              AND doctorid = p_did
              AND EXTRACT(HOUR  FROM date)::integer = v_currenthour
        ) THEN
            v_count := v_count + 1;

            IF v_currenthour < 12 THEN
                v_tempt    := ':00 AM';
                v_temphour := v_currenthour;
            ELSIF v_currenthour = 12 THEN
                v_tempt    := ':00 PM';
                v_temphour := v_currenthour;
            ELSE
                v_tempt    := ':00 PM';
                v_temphour := v_currenthour - 12;
            END IF;

            v_hourslist := v_hourslist || v_temphour::varchar(5) || v_tempt || ',';
        END IF;

        v_currenthour := v_currenthour + 1;
    END LOOP;

    OPEN ref_slots FOR
        SELECT splitdata AS "Free Slots"
        FROM dbo.fnsplitstring(v_hourslist, ',');

    OPEN ref_count FOR
        SELECT v_count AS count;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievepatientdata
-- Original: [dbo].[RetrievePatientData]
-- Changes:
--   - Multiple OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - DATEDIFF(YEAR, BirthDate, GETDATE()) → EXTRACT(YEAR FROM AGE(...))
--   - @birthDate varchar(10) output → p_birthdate varchar(10) (stored as text)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievepatientdata(
    p_id            integer,
    OUT p_name      varchar(30),
    OUT p_phone     char(11),
    OUT p_address   varchar(40),
    OUT p_birthdate varchar(10),
    OUT p_age       integer,
    OUT p_gender    char(1)
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    SELECT
        pt.name,
        pt.phone,
        pt.address,
        pt.gender,
        EXTRACT(YEAR FROM AGE(CURRENT_TIMESTAMP, pt.birthdate))::integer,
        pt.birthdate::varchar(10)
    INTO p_name, p_phone, p_address, p_gender, p_age, p_birthdate
    FROM dbo.patient pt
    WHERE pt.patientid = p_id;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievepatientnotifications
-- Original: [dbo].[RetrievePatientNotifications]
-- Changes:
--   - Multiple OUT parameters + complex logic → RETURNS SETOF record
--   - CONVERT(VARCHAR(19), [date]) → TO_CHAR(date, 'YYYY-MM-DD HH24:MI:SS')
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievepatientnotifications(
    p_pid       integer,
    OUT p_dname  varchar(30),
    OUT p_timings varchar(30),
    OUT p_count  integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
DECLARE
    v_astatus integer;
    v_aid     integer;
BEGIN
    IF EXISTS (SELECT 1 FROM dbo.appointment WHERE patientid = p_pid AND patientnotification = 2) THEN
        SELECT appointment_status, appointid
        INTO v_astatus, v_aid
        FROM dbo.appointment
        WHERE patientid = p_pid AND patientnotification = 2;

        IF v_astatus = 1 OR v_astatus = 3 THEN
            IF v_astatus = 3 THEN
                p_count := 3;
            ELSE
                p_count := 1;
            END IF;

            SELECT d.name, TO_CHAR(a.date, 'YYYY-MM-DD HH24:MI:SS')
            INTO p_dname, p_timings
            FROM dbo.appointment a
            JOIN dbo.doctor d ON a.doctorid = d.doctorid
            WHERE a.appointid = v_aid;

            UPDATE dbo.appointment
            SET patientnotification = 1
            WHERE appointid = v_aid;

        ELSIF v_astatus = 4 THEN
            SELECT d.name, TO_CHAR(a.date, 'YYYY-MM-DD HH24:MI:SS')
            INTO p_dname, p_timings
            FROM dbo.appointment a
            JOIN dbo.doctor d ON a.doctorid = d.doctorid
            WHERE a.appointid = v_aid;

            p_count := 2;

            DELETE FROM dbo.appointment WHERE appointid = v_aid;
        ELSE
            p_count := 0;
        END IF;
    ELSE
        p_count := 0;
    END IF;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievependingfeedback
-- Original: [dbo].[retrievePendingFeedback]
-- Changes:
--   - Four OUT parameters → RETURNS SETOF record with RETURN NEXT
--   - CONVERT(VARCHAR(19), [date]) → TO_CHAR(date, 'YYYY-MM-DD HH24:MI:SS')
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievependingfeedback(
    p_pid       integer,
    OUT p_dname  varchar(30),
    OUT p_timings varchar(30),
    OUT p_aid    integer,
    OUT p_count  integer
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM dbo.appointment
        WHERE patientid = p_pid
          AND feedbackstatus = 2
          AND appointment_status = 3
    ) THEN
        p_count := 1;

        SELECT d.name, TO_CHAR(a.date, 'YYYY-MM-DD HH24:MI:SS'), a.appointid
        INTO p_dname, p_timings, p_aid
        FROM dbo.appointment a
        JOIN dbo.doctor d ON a.doctorid = d.doctorid
        WHERE a.patientid = p_pid
          AND a.feedbackstatus = 2
          AND a.appointment_status = 3;
    ELSE
        p_count := 0;
    END IF;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievephistory
-- Original: [dbo].[retrievePHistory]
-- Changes: Simple SELECT; RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievephistory(
    p_did integer
)
RETURNS TABLE(
    name         varchar(30),
    disease      varchar(100),
    progress     varchar(100),
    prescription varchar(100)
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.name,
        a.disease,
        a.progress,
        a.prescription
    FROM dbo.appointment a
    JOIN dbo.patient p ON a.patientid = p.patientid
    WHERE a.doctorid = p_did
      AND a.appointment_status = 3;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.retrievetreatmenthistory
-- Original: [dbo].[RetrieveTreatmentHistory]
-- Changes:
--   - Has both a result set AND an OUT parameter (@count) → REFCURSOR pattern
--   - CONVERT(VARCHAR(11), [date], 106) → TO_CHAR(date, 'DD Mon YYYY')
-- BREAKING CHANGE NOTE: Application must read two cursors:
--   ref_history → treatment history rows
--   ref_count   → single row with count value
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.retrievetreatmenthistory(
    p_pid           integer,
    OUT ref_history REFCURSOR,
    OUT ref_count   REFCURSOR
)
RETURNS SETOF record
LANGUAGE plpgsql
AS $$
BEGIN
    OPEN ref_history FOR
        SELECT
            TO_CHAR(a.date, 'DD Mon YYYY') AS "Date",
            d.name                          AS "Doctor's Name",
            a.disease                       AS "Diagnosed Disease",
            a.progress                      AS "Progress Made",
            a.prescription
        FROM dbo.appointment a
        JOIN dbo.doctor d ON a.doctorid = d.doctorid
        WHERE a.patientid = p_pid
          AND a.appointment_status = 3;

    OPEN ref_count FOR
        SELECT COUNT(*) AS count
        FROM dbo.appointment
        WHERE patientid = p_pid
          AND appointment_status = 3;

    RETURN NEXT;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.sp_deleteprofileimage
-- Original: [dbo].[sp_DeleteProfileImage]
-- Changes:
--   - SET NOCOUNT ON → not needed in PostgreSQL
--   - @@ROWCOUNT → GET DIAGNOSTICS rows_affected = ROW_COUNT
--   - Returns rows affected as a result set → RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.sp_deleteprofileimage(
    p_loginid integer
)
RETURNS TABLE(rowsaffected bigint)
LANGUAGE plpgsql
AS $$
DECLARE
    v_rows bigint;
BEGIN
    DELETE FROM dbo.profileimages WHERE loginid = p_loginid;
    GET DIAGNOSTICS v_rows = ROW_COUNT;
    RETURN QUERY SELECT v_rows;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.sp_getprofileimage
-- Original: [dbo].[sp_GetProfileImage]
-- Changes: Simple SELECT; RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.sp_getprofileimage(
    p_loginid integer
)
RETURNS TABLE(
    imageid         integer,
    loginid         integer,
    s3bucketname    varchar(100),
    s3key           varchar(500),
    filename        varchar(255),
    fileextension   varchar(10),
    contenttype     varchar(100),
    filesizebytes   bigint,
    s3url           varchar(1000),
    uploadedat      timestamp without time zone,
    updatedat       timestamp without time zone
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        pi.imageid, pi.loginid, pi.s3bucketname, pi.s3key, pi.filename,
        pi.fileextension, pi.contenttype, pi.filesizebytes, pi.s3url,
        pi.uploadedat, pi.updatedat
    FROM dbo.profileimages pi
    WHERE pi.loginid = p_loginid;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.sp_upsertprofileimage
-- Original: [dbo].[sp_UpsertProfileImage]
-- Changes:
--   - SCOPE_IDENTITY() → lastval() via RETURNING clause
--   - Returns new ImageID as result set → RETURNS TABLE
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.sp_upsertprofileimage(
    p_loginid       integer,
    p_s3bucketname  varchar(100),
    p_s3key         varchar(500),
    p_filename      varchar(255),
    p_fileextension varchar(10),
    p_contenttype   varchar(100),
    p_filesizebytes bigint,
    p_s3url         varchar(1000) DEFAULT NULL
)
RETURNS TABLE(imageid integer)
LANGUAGE plpgsql
AS $$
DECLARE
    v_imageid integer;
BEGIN
    -- Hard delete existing profile image if any
    DELETE FROM dbo.profileimages WHERE loginid = p_loginid;

    -- Insert new profile image and capture new ID
    INSERT INTO dbo.profileimages (
        loginid, s3bucketname, s3key, filename, fileextension,
        contenttype, filesizebytes, s3url
    )
    VALUES (
        p_loginid, p_s3bucketname, p_s3key, p_filename, p_fileextension,
        p_contenttype, p_filesizebytes, p_s3url
    )
    RETURNING profileimages.imageid INTO v_imageid;

    RETURN QUERY SELECT v_imageid;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.storefeedback
-- Original: [dbo].[storeFeedback]
-- Changes: Multiple UPDATEs; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.storefeedback(
    p_aid integer
)
RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    v_did  integer;
    v_ri   double precision;
    v_pt   integer;
    v_avg  double precision;
BEGIN
    SELECT doctorid INTO v_did
    FROM dbo.appointment
    WHERE appointid = p_aid;

    SELECT reputeindex, patients_treated
    INTO v_ri, v_pt
    FROM dbo.doctor
    WHERE doctorid = v_did;

    v_avg := (v_ri * (v_pt - 1)) / v_pt;

    UPDATE dbo.doctor
    SET reputeindex = v_avg
    WHERE doctorid = v_did;

    UPDATE dbo.appointment
    SET feedbackstatus = 1
    WHERE appointid = p_aid;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.todays_appointments
-- Original: [dbo].[TODAYS_APPOINTMENTS]
-- Changes:
--   - ISNULL(CONVERT(varchar(2), col), 'NA') → COALESCE(col::varchar, 'NA')
--   - DATEDIFF(DAY, A.Date, GETDATE()) = 0 → DATE(a.date) = CURRENT_DATE
--   - RETURNS TABLE for result set
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.todays_appointments(
    p_doc_id integer
)
RETURNS TABLE(
    appointid           integer,
    patient_name        varchar(30),
    date                timestamp without time zone,
    bill_amount         varchar,
    bill_status         varchar,
    disease             varchar,
    progress            varchar,
    prescription        varchar,
    appointment_status  integer
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        a.appointid,
        p.name                                          AS patient_name,
        a.date,
        COALESCE(a.bill_amount::varchar, 'NA')          AS bill_amount,
        COALESCE(a.bill_status::varchar, 'NA')          AS bill_status,
        COALESCE(a.disease::varchar, 'NA')              AS disease,
        COALESCE(a.progress::varchar, 'NA')             AS progress,
        COALESCE(a.prescription::varchar, 'NA')         AS prescription,
        a.appointment_status
    FROM dbo.appointment a
    JOIN dbo.patient p ON a.patientid = p.patientid
    WHERE a.doctorid = p_doc_id
      AND a.appointment_status = 1
      AND DATE(a.date) = CURRENT_DATE;
END;
$$;

-- -----------------------------------------------------------------------------
-- Function: dbo.updateprescription
-- Original: [dbo].[UpdatePrescription]
-- Changes: Simple UPDATE; RETURNS void
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION dbo.updateprescription(
    p_docid       integer,
    p_appointid   integer,
    p_disease     varchar(30),
    p_progress    varchar(50),
    p_prescription varchar(60)
)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
    UPDATE dbo.appointment
    SET disease             = p_disease,
        progress            = p_progress,
        prescription        = p_prescription,
        appointment_status  = 3,
        patientnotification = 2,
        feedbackstatus      = 2
    WHERE appointid = p_appointid;
END;
$$;

-- =============================================================================
-- SECTION 9: EVENT TRIGGERS (DDL Triggers)
-- =============================================================================
-- Original: DontDeleteFunction, DontDeleteProcedure, DontDeleteTable, DontDeleteView
-- These were SQL Server DDL triggers ON DATABASE FOR DROP_FUNCTION/PROCEDURE/TABLE/VIEW
-- PostgreSQL equivalent: event triggers using ddl_command_start
-- NOTE: Event triggers require superuser or event_trigger privilege.
--       They fire on ddl_command_start and can raise exceptions to prevent DDL.
-- =============================================================================

-- Trigger function: prevent DROP FUNCTION
CREATE OR REPLACE FUNCTION dbo.trg_prevent_drop_function()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF tg_tag = 'DROP FUNCTION' THEN
        RAISE EXCEPTION 'Function Deletion is Not Allowed';
    END IF;
END;
$$;

CREATE EVENT TRIGGER dontdeletefunction
    ON ddl_command_start
    WHEN TAG IN ('DROP FUNCTION')
    EXECUTE FUNCTION dbo.trg_prevent_drop_function();

-- Trigger function: prevent DROP PROCEDURE
CREATE OR REPLACE FUNCTION dbo.trg_prevent_drop_procedure()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF tg_tag = 'DROP FUNCTION' OR tg_tag = 'DROP PROCEDURE' THEN
        RAISE EXCEPTION 'Procedure Deletion Not Allowed.';
    END IF;
END;
$$;

CREATE EVENT TRIGGER dontdeleteprocedure
    ON ddl_command_start
    WHEN TAG IN ('DROP FUNCTION', 'DROP PROCEDURE')
    EXECUTE FUNCTION dbo.trg_prevent_drop_procedure();

-- Trigger function: prevent DROP TABLE
CREATE OR REPLACE FUNCTION dbo.trg_prevent_drop_table()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF tg_tag = 'DROP TABLE' THEN
        RAISE EXCEPTION 'Table Deletion Not Allowed.';
    END IF;
END;
$$;

CREATE EVENT TRIGGER dontdeletetable
    ON ddl_command_start
    WHEN TAG IN ('DROP TABLE')
    EXECUTE FUNCTION dbo.trg_prevent_drop_table();

-- Trigger function: prevent DROP VIEW
CREATE OR REPLACE FUNCTION dbo.trg_prevent_drop_view()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF tg_tag = 'DROP VIEW' THEN
        RAISE EXCEPTION 'View Deletion Not Allowed.';
    END IF;
END;
$$;

CREATE EVENT TRIGGER dontdeleteview
    ON ddl_command_start
    WHEN TAG IN ('DROP VIEW')
    EXECUTE FUNCTION dbo.trg_prevent_drop_view();

-- =============================================================================
-- SECTION 10: POST-MIGRATION VALIDATION
-- =============================================================================
-- Run this block after migration to verify sequences are in sync:
-- DO $$
-- DECLARE r RECORD;
-- BEGIN
--   FOR r IN
--     SELECT c.table_schema || '.' || c.table_name AS tname,
--            c.column_name,
--            pg_get_serial_sequence(c.table_schema || '.' || c.table_name, c.column_name) AS seq
--     FROM information_schema.columns c
--     WHERE c.column_default LIKE 'nextval%'
--   LOOP
--     IF r.seq IS NOT NULL THEN
--       EXECUTE format('SELECT setval(%L, COALESCE(MAX(%I), 1), true) FROM %s',
--                      r.seq, r.column_name, r.tname);
--     END IF;
--   END LOOP;
-- END $$;

ANALYZE;